# Mathematics for Machine Learning: Linear Algebra
## Week4
## Module 4:

### Matrices, Multiple Mappings, basis transformation

### Introduction: Einstein summation convention and the symmetry of the dot product
### Non-square matrix multiplication
#### Practice Quiz

In [1]:
import numpy as np
from sympy import solve, Poly, Eq, Function, exp

from sympy.abc import x, y, z, a, b


In [2]:
# Q1-2
A = np.array([[1, 2 , 3],[4, 0, 1]])
B = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])

In [3]:
C = A@B
print(C)

[[4 3 5]
 [5 4 1]]


In [4]:
# Q3:
np.array([2, 4, 5, 6,])@np.array([1, 3, 2, 1])

30

In [5]:
# Q4:
np.matrix('1; 3; 2; 1')@np.matrix('2, 4, 5, 6')

matrix([[ 2,  4,  5,  6],
        [ 6, 12, 15, 18],
        [ 4,  8, 10, 12],
        [ 2,  4,  5,  6]])

In [6]:
# Q5:
np.matrix('2,-1;0, 3; 1, 0')@np.matrix([[0, 1, 4, -1],[-2, 0, 0, 2]])

matrix([[ 2,  2,  8, -4],
        [-6,  0,  0,  6],
        [ 0,  1,  4, -1]])

In [7]:
# Q7
np.eye(2)@np.matrix([[1, 2, 3],[4, 5, 6]])

matrix([[1., 2., 3.],
        [4., 5., 6.]])

## Orthogonal matrices

### The Gram–Schmidt process

In [8]:
from grahm_shmidt import *


In [9]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)
gsBasis4(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [10]:
# Once you've done Gram-Schmidt once,
# doing it again should give you the same result. Test this:
U = gsBasis4(V)
gsBasis4(U)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [11]:
# Try the general function too.
gsBasis(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [12]:
assert (gsBasis(V) == gsBasis4(V)).all

In [13]:
# See what happens for non-square matrices
A = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
gsBasis(A)

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [14]:
dimensions(A)

3.0

In [15]:
B = np.array([[6,2,1,7,5],
              [2,8,5,-4,1],
              [1,-6,3,2,8]], dtype=np.float_)
gsBasis(B)

array([[ 0.93704257, -0.12700832, -0.32530002,  0.        ,  0.        ],
       [ 0.31234752,  0.72140727,  0.61807005,  0.        ,  0.        ],
       [ 0.15617376, -0.6807646 ,  0.71566005,  0.        ,  0.        ]])

In [16]:
dimensions(B)

3.0

In [17]:
# Now let's see what happens when we have one vector that is a linear combination of the others.
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [18]:
dimensions(C)

2.0