# Mathematics for Machine Learning: Linear Algebra
## Week4
## Module 4:

### Matrices, Multiple Mappings, basis transformation

### Introduction: Einstein summation convention and the symmetry of the dot product
### Non-square matrix multiplication
#### Practice Quiz

In [1]:
import numpy as np

In [2]:
# Q1-2
A = np.array([[1, 2 , 3],[4, 0, 1]])
B = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])

In [3]:
C = A@B
print(C)

[[4 3 5]
 [5 4 1]]


In [4]:
# Q3:
np.array([2, 4, 5, 6,])@np.array([1, 3, 2, 1])

30

In [5]:
# Q4:
np.matrix('1; 3; 2; 1')@np.matrix('2, 4, 5, 6')

matrix([[ 2,  4,  5,  6],
        [ 6, 12, 15, 18],
        [ 4,  8, 10, 12],
        [ 2,  4,  5,  6]])

In [6]:
# Q5:
np.matrix('2,-1;0, 3; 1, 0')@np.matrix([[0, 1, 4, -1],[-2, 0, 0, 2]])

matrix([[ 2,  2,  8, -4],
        [-6,  0,  0,  6],
        [ 0,  1,  4, -1]])

In [7]:
# Q7
np.eye(2)@np.matrix([[1, 2, 3],[4, 5, 6]])

matrix([[1., 2., 3.],
        [4., 5., 6.]])

## Orthogonal matrices

### The Gram–Schmidt process

In [8]:
from grahm_shmidt import *


In [9]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)
gsBasis4(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [10]:
# Once you've done Gram-Schmidt once,
# doing it again should give you the same result. Test this:
U = gsBasis4(V)
gsBasis4(U)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [11]:
# Try the general function too.
gsBasis(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [12]:
assert (gsBasis(V) == gsBasis4(V)).all

In [13]:
# See what happens for non-square matrices
A = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
gsBasis(A)

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [14]:
dimensions(A)

3.0

In [15]:
B = np.array([[6,2,1,7,5],
              [2,8,5,-4,1],
              [1,-6,3,2,8]], dtype=np.float_)
gsBasis(B)

array([[ 0.93704257, -0.12700832, -0.32530002,  0.        ,  0.        ],
       [ 0.31234752,  0.72140727,  0.61807005,  0.        ,  0.        ],
       [ 0.15617376, -0.6807646 ,  0.71566005,  0.        ,  0.        ]])

In [16]:
dimensions(B)

3.0

In [17]:
# Now let's see what happens when we have one vector that is a linear combination of the others.
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [18]:
dimensions(C)

2.0

## Example: Reflecting in a plane

In [19]:
v1 = np.array([1, 1, 1])
v2 = np.array([2, 0, 1])
v3 = np.array([3, 1, -1])
A = np.array([v1,v2,v3]).T
print(A)

[[ 1  2  3]
 [ 1  0  1]
 [ 1  1 -1]]


In [20]:
B = gsBasis(A)
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)
print(B)
e1 = B[:,0]
e2 = B[:,1]
e3 = B[:,2]
assert abs(e1@e2) < 1e-14 # to make sure it is orthonormal
assert abs(e1@e3) < 1e-14
assert abs(e2@e3) < 1e-14

[[ 0.5774  0.7071  0.4082]
 [ 0.5774 -0.7071  0.4082]
 [ 0.5774 -0.     -0.8165]]


In [21]:
r = np.array([2,3,5])
T_e = np.eye(3)
T_e[2,2] = -1
r_e = B.T@r
r_e_p = T_e@r_e
r_p = B @r_e_p

In [22]:
T = B@T_e@B.T

In [23]:
assert (r_p - T@r < 1e-14 ).all

In [24]:
print(T)
print(r_p)
r_p - 1/3*np.array([11,14,5])

[[ 0.6667 -0.3333  0.6667]
 [-0.3333  0.6667  0.6667]
 [ 0.6667  0.6667 -0.3333]]
[3.6667 4.6667 1.6667]


array([0., 0., 0.])

In [25]:
# In this function, you will return the transformation matrix T,
# having built it out of an orthonormal basis set E that you create from Bear's Basis
# and a transformation matrix in the mirror's coordinates TE.
def build_reflection_matrix(bearBasis) : # The parameter bearBasis is a 2×2 matrix that is passed to the function.
    # Use the gsBasis function on bearBasis to get the mirror's orthonormal basis.
    E = gsBasis(bearBasis)
    # Write a matrix in component form that performs the mirror's reflection in the mirror's basis.
    # Recall, the mirror operates by negating the last component of a vector.
    # Replace a,b,c,d with appropriate values
    TE = np.array([[1, 0],
                   [0, -1]])
    # Combine the matrices E and TE to produce your transformation matrix.
    T = E.T@TE@E
    # Finally, we return the result. There is no need to change this line.
    return T

## Test your code before submission
To test the code you've written above, run the cell (select the cell above, then press the play button [ ▶| ] or press shift-enter).
You can then use the code below to test out your function.
You don't need to submit this cell; you can edit and run it as much as you like.

The code below will show a picture of Panda Bear.
If you have correctly implemented the function above, you will also see Bear's reflection in his mirror.
The orange axes are Bear's basis, and the pink axes are the mirror's orthonormal basis.

In [26]:
# First load Pyplot, a graph plotting library.
%matplotlib inline
import matplotlib.pyplot as plt

# This is the matrix of Bear's basis vectors.
# (When you've done the exercise once, see what happns when you change Bear's basis.)
bearBasis = np.array(
    [[1,   -1],
     [1.5, 2]])
# This line uses your code to build a transformation matrix for us to use.
T = build_reflection_matrix(bearBasis)

# Bear is drawn as a set of polygons, the vertices of which are placed as a matrix list of column vectors.
# We have three of these non-square matrix lists: bear_white_fur, bear_black_fur, and bear_face.
# We'll make new lists of vertices by applying the T matrix you've calculated.
reflected_bear_white_fur = T @ bear_white_fur
reflected_bear_black_fur = T @ bear_black_fur
reflected_bear_face = T @ bear_face

# This next line runs a code to set up the graphics environment.
ax = draw_mirror(bearBasis)

# We'll first plot Bear, his white fur, his black fur, and his face.
ax.fill(bear_white_fur[0], bear_white_fur[1], color=bear_white, zorder=1)
ax.fill(bear_black_fur[0], bear_black_fur[1], color=bear_black, zorder=2)
ax.plot(bear_face[0], bear_face[1], color=bear_white, zorder=3)

# Next we'll plot Bear's reflection.
ax.fill(reflected_bear_white_fur[0], reflected_bear_white_fur[1], color=bear_white, zorder=1)
ax.fill(reflected_bear_black_fur[0], reflected_bear_black_fur[1], color=bear_black, zorder=2)
ax.plot(reflected_bear_face[0], reflected_bear_face[1], color=bear_white, zorder=3);

NameError: name 'bear_white_fur' is not defined